name: avia_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  retrofit: ^4.1.0
  equatable: ^2.0.5
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  get_it: ^7.6.7
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  retrofit_generator: ^8.1.0


flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/icons/hotels_bnb_icon.png
    - lib/assets/images/icons/location_bnb_icon.png
    - lib/assets/images/icons/plane_bnb_icon.png
    - lib/assets/images/icons/profile_bnb_icon.png
    - lib/assets/images/icons/subscription_bnb_icon.png
    - lib/assets/images/icons/search_icon.png
    - lib/assets/images/icons/plane_icon.png
    - lib/assets/images/icons/calendar_icon.png
    - lib/assets/images/icons/fire_icon.png
    - lib/assets/images/icons/globe_icon.png
    - lib/assets/images/icons/route_icon.png
    - lib/assets/images/icons/clear_mark_icon.png
    - lib/assets/images/music_ticket_1.jpg
    - lib/assets/images/music_ticket_2.jpg
    - lib/assets/images/music_ticket_3.jpg
    - lib/assets/images/phuket_photo.png
    - lib/assets/images/sochi_photo.png
    - lib/assets/images/stambul_photo.png


  fonts:
    - family: SF_Pro_Display
      fonts:
        - asset: lib/assets/fonts/SF-Pro-Display-Regular.otf
